### ISSUE TITLE
TNP Limitless Modpack updated and now gamecrash when striking with Dragonsteel Sword from SilentGear

### ISSUE THREAD

**Issue by x0tempus0x** [Partonetrain/iafgear#7]
Hi,

As written in the header, i updated to the newest version and constantly my games crashes, as soon as i try to hit a mob with a silentgear sword, made of dragoningots. It has some enchantments on it, but this was no problem in TNP Limitless1.10.4 (and i downgraded back to 1.10.4 because of the crashs).

Wrote this in the TNP Limitless modpack, but modpack author suggested, that i should write it here.

[crash-2021-06-13_08.06.02-server.txt](https://github.com/Partonetrain/iafgear/files/6649858/crash-2021-06-13_08.06.02-server.txt)

Gz. Temp

**Comment by Partonetrain** [comment]
I think Ice and Fire recently had a refactor and broke stuff. I'll see if I can't get this fixed by this weekend
