### ISSUE TITLE
Some materials error and don't load with newest SilentGear

### ISSUE THREAD

**Issue by FrostLord001** [Partonetrain/iafgear#8]
Probably this:
[2021-07-13-15.log](https://github.com/Partonetrain/iafgear/files/6817754/2021-07-13-15.log)

**Comment by Partonetrain** [comment]
Does this happen with iafgear-1.16.5-1.0.3.jar? You aren't using the latest version.

**Comment by FrostLord001** [comment]
What do you mean? I am currently looking at curseforge and the newest version is 1.0.3.

**Comment by DerShiho** [comment]
I have the same Issue, and it does happen with iafgear-1.16.5-1.0.3.jar
[latest.log](https://github.com/Partonetrain/iafgear/files/6825935/latest.log)

**Comment by Partonetrain** [comment]
@FrostLord001 the version you are using in the log you gave (2021-07-13-14.log) was 1.0.2

Looks like SGear got a refactor, I will look into fixing this this weekend.

**Comment by Partonetrain** [comment]
Uploaded a fix (iafgear-1.16.5-1.0.4) to CurseForge now. If more issues come up, please create a new issue.
